### ISSUE TITLE
line 289, in main\nAttributeError: 'NoneType' object has no attribute 'lower'\n",

### ISSUE THREAD

**Issue by infragilis** [Cisco-SAN/MDS_Ansible_Modules#1]
cisco MDS 9148 FC / 5.0.1a ansible 2.9.0 / python version = 2.7.5

---
- hosts: localhost
  gather_facts: false
  vars_files:
   vars.yml
  vars:
    creds:
      host: "{{ inventory_hostname }}"
      username: "{{ mdsuser }}"
      password: "{{ mdspass }}"
      transport: cli
  name: test
  tasks:
    - name: Test that device alias module works
      nxos_devicealias:
          distribute: yes
          mode: enhanced
          da:
              - { name: 'test1_add', pwwn: '56:2:22:11:22:88:11:67'}
              - { name: 'test2_add', pwwn: '65:22:22:11:22:22:11:d'}
              - { name: 'abc', remove: True}
              - { name: 't$yz', remove: True}
          provider: "{{ creds }}"
      register: result
    - debug: var=result

The full traceback is:
Traceback (most recent call last):
  File "/home/xxx/.ansible/tmp/ansible-tmp-1581366192.39-223748165152706/AnsiballZ_nxos_devicealias.py", line 102, in <module>
    _ansiballz_main()
  File "/home/xxx/.ansible/tmp/ansible-tmp-1581366192.39-223748165152706/AnsiballZ_nxos_devicealias.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/xxx/.ansible/tmp/ansible-tmp-1581366192.39-223748165152706/AnsiballZ_nxos_devicealias.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.nxos_devicealias', init_globals=None, run_name='__main__', alter_sys=False)
  File "/usr/lib64/python2.7/runpy.py", line 180, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_nxos_devicealias_payload_oq_FK3/ansible_nxos_devicealias_payload.zip/ansible/modules/nxos_devicealias.py", line 504, in <module>
  File "/tmp/ansible_nxos_devicealias_payload_oq_FK3/ansible_nxos_devicealias_payload.zip/ansible/modules/nxos_devicealias.py", line 289, in main
AttributeError: 'NoneType' object has no attribute 'lower'

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/xxx/.ansible/tmp/ansible-tmp-1581366192.39-223748165152706/AnsiballZ_nxos_devicealias.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/xxx/.ansible/tmp/ansible-tmp-1581366192.39-223748165152706/AnsiballZ_nxos_devicealias.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/xxx/.ansible/tmp/ansible-tmp-1581366192.39-223748165152706/AnsiballZ_nxos_devicealias.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.nxos_devicealias', init_globals=None, run_name='__main__', alter_sys=False)\n  File \"/usr/lib64/python2.7/runpy.py\", line 180, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_nxos_devicealias_payload_oq_FK3/ansible_nxos_devicealias_payload.zip/ansible/modules/nxos_devicealias.py\", line 504, in <module>\n  File \"/tmp/ansible_nxos_devicealias_payload_oq_FK3/ansible_nxos_devicealias_payload.zip/ansible/modules/nxos_devicealias.py\", line 289, in main\nAttributeError: 'NoneType' object has no attribute 'lower'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Comment by srbharadwaj** [comment]
looking into it..

**Comment by srbharadwaj** [comment]
Fixed this issue by the commit #9bb37d0
